# Generated by Django 4.0.6 on 2022-07-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Ícone da categoria', null=True, upload_to='category/icon/', verbose_name='Ícone'),
        ),
    ]
