# Generated by Django 4.0.6 on 2022-08-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_remove_order_region'),
        ('account', '0002_rename_profile_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.region'),
        ),
    ]
