# Generated by Django 4.0.6 on 2022-08-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_store_url_alter_store_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Endereço:'),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Cidade:'),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store/logo/', verbose_name='Logo da loja:'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da loja:'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(help_text='Este numero será utilizado para efetuar o envio dos pedidos', max_length=100, verbose_name='Telefone:'),
        ),
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(max_length=100, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='store',
            name='zipcode',
            field=models.CharField(max_length=100, verbose_name='CEP:'),
        ),
    ]
