# Generated by Django 4.0.6 on 2022-07-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('P', 'Pedido realizado'), ('M', 'Preparando pedido'), ('E', 'Saiu para entrega')], default='P', max_length=1),
        ),
    ]
