# Generated by Django 4.0.6 on 2022-07-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_payment_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=256, verbose_name='Nome completo:'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='Telefone:'),
        ),
    ]
