# Generated by Django 4.0.6 on 2022-07-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_order_order_items_order_order_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-name',), 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
