# Generated by Django 4.0.6 on 2022-08-11 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_category_name'),
        ('order', '0018_remove_order_address_remove_order_complement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.basemodel')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Item Adicional:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Item Adicional:')),
            ],
            options={
                'verbose_name': 'Additional',
                'verbose_name_plural': 'Additionals',
                'ordering': ('-name',),
            },
            bases=('products.basemodel',),
        ),
    ]
