# Generated by Django 4.0.6 on 2022-08-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='additional',
            field=models.ManyToManyField(blank=True, to='order.additional'),
        ),
    ]
