# Generated by Django 4.0.6 on 2022-08-11 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=256, verbose_name='Nome completo:')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='Telefone:')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Endereço:')),
                ('zipcode', models.CharField(default='', max_length=100, verbose_name='CEP:')),
                ('number', models.CharField(default='', max_length=50, verbose_name='Número:')),
                ('district', models.CharField(default='', max_length=100, verbose_name='Bairro:')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
