# Generated by Django 4.0.6 on 2022-08-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_remove_order_region'),
        ('account', '0005_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='client',
            name='district',
        ),
        migrations.RemoveField(
            model_name='client',
            name='number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='region',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zipcode',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Endereço:')),
                ('zipcode', models.CharField(default='', max_length=100, verbose_name='CEP:')),
                ('number', models.CharField(default='', max_length=50, verbose_name='Número:')),
                ('district', models.CharField(default='', max_length=100, verbose_name='Bairro:')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento:')),
                ('region', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.region')),
            ],
        ),
    ]
