# Generated by Django 4.0.6 on 2022-08-18 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_client_address_remove_client_complement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.address', verbose_name='Endereço'),
        ),
    ]
