# Generated by Django 4.0.6 on 2022-08-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_address_options_client_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='street',
        ),
    ]
