# Generated by Django 4.0.6 on 2022-08-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do endereço:'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Bairro:'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Número:'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Rua:'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='CEP:'),
        ),
    ]
