# Generated by Django 4.0.6 on 2022-07-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_region_remove_order_email_remove_order_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complement',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Complemento:'),
        ),
    ]
