# Generated by Django 4.0.6 on 2022-07-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento:'),
        ),
    ]
