# Generated by Django 4.0.6 on 2022-07-16 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_full_name_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.orderitem'),
        ),
    ]
