# Generated by Django 4.0.6 on 2022-07-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pedido realizado'), ('M', 'Preparando pedido'), ('E', 'Saiu para entrega'), ('F', 'Pedido Entregue')], default='P', max_length=1, verbose_name='Status do Pedido:'),
        ),
    ]
