# Generated by Django 4.0.6 on 2022-08-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_orderitem_additional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='region',
        ),
    ]
