# Generated by Django 4.0.6 on 2022-07-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.CreateModel(
            name='Ordered',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.basemodel')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço:')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total:')),
                ('product', models.ManyToManyField(related_name='items', to='products.products')),
            ],
            options={
                'verbose_name': 'Ordered',
                'verbose_name_plural': 'Ordered',
                'ordering': ('-created_at',),
            },
            bases=('products.basemodel',),
        ),
    ]
