# Generated by Django 4.0.6 on 2022-07-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_slug_products_slug_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço:'),
        ),
    ]
