# Generated by Django 4.0.6 on 2022-07-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Recomendamos o tamanho de 64x64 pixels.', null=True, upload_to='category/icon/', verbose_name='Ícone'),
        ),
    ]
