# Generated by Django 4.0.6 on 2022-08-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_products_is_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Produto Ativo?'),
        ),
    ]
