# Generated by Django 4.0.6 on 2022-08-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_products_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
